### ISSUE TITLE
Documenting how to run it without being signed.

### ISSUE THREAD

**Issue by oderwat** [coheff/alfred-hunt-tor#1]
You probably want to tell people (in a README for the workflow and here) what they need to do to run your workflow because it won't start as it is not being signed.

**Comment by coheff** [comment]
Good call out @oderwat. Updated README with the following -

"If running on macOS Catalina or later, you _**MUST**_ add Alfred to the list of security exceptions for running unsigned software. Step-by-step instructions are available on the awgo wiki [here](https://github.com/deanishe/awgo/wiki/Catalina)".

**Comment by oderwat** [comment]
You can also start your application once ("with terminal") and except to open it. This way, Alfred will not be able to run just anything. To achieve it, you can install the workflow and then right click it to open the folder in Finder. Then right-click the 'alfred-hunt-tor' and open with Terminal. Then agree to open it. It will run and complain, not being started by Alfred. After that, the workflow will work (until an update of the executable).

**Comment by coheff** [comment]
TIL. Thank you, that’s extremely helpful. Is it ok if I add your comment to the README?

**Comment by oderwat** [comment]
Sure. And sorry, that I am too lazy to make a PR.

**Comment by coheff** [comment]
No problem at all! Updated. 

Thanks again, appreciate it.
